"""Generate markdown summary logs for pipeline runs."""
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from src.models import CampaignBrief

log = logging.getLogger(__name__)


def write_summary_log(
    run_dir: Path,
    run_id: str,
    brief: CampaignBrief,
    log_type: str,
    result: dict[str, Any] | None = None,
    generated_assets: list[str] | None = None,
) -> Path:
    """Write a markdown summary log for a pipeline run.
    
    Args:
        run_dir: Directory where the run artifacts are saved.
        run_id: Unique run identifier (timestamp).
        brief: Campaign brief that was processed.
        log_type: Type of run - "asset_generation" or "campaign_generation".
        result: Result dictionary from campaign generation (optional).
        generated_assets: List of generated asset filenames for asset generation runs (optional).
        
    Returns:
        Path to the created summary log file.
        
    Raises:
        ValueError: If log_type is not recognized.
    """
    if log_type not in ("asset_generation", "campaign_generation"):
        raise ValueError(f"Invalid log_type: {log_type}. Must be 'asset_generation' or 'campaign_generation'")
    
    summary_path = run_dir / "SUMMARY.md"
    
    with open(summary_path, "w", encoding="utf-8") as f:
        # Header
        f.write(f"# Pipeline Run Summary\n\n")
        f.write(f"**Run ID:** `{run_id}`  \n")
        f.write(f"**Timestamp:** {datetime.now().strftime('%B %d, %Y at %I:%M:%S %p')}  \n")
        f.write(f"**Run Type:** {log_type.replace('_', ' ').title()}  \n\n")
        
        # Campaign Information
        f.write(f"## Campaign Information\n\n")
        f.write(f"- **Campaign Name:** {brief.campaign_name}\n")
        f.write(f"- **Region:** {brief.region}\n")
        if brief.language:
            f.write(f"- **Language:** {brief.language}\n")
        f.write(f"- **Audience:** {brief.audience}\n")
        f.write(f"- **Message:** {brief.message}\n")
        f.write(f"- **Aspect Ratios:** {', '.join(brief.aspect_ratios)}\n\n")
        
        # Products
        f.write(f"## Products ({len(brief.products)})\n\n")
        for i, product in enumerate(brief.products, 1):
            f.write(f"### {i}. {product.name}\n\n")
            f.write(f"- **Slug:** `{product.slug}`\n")
            f.write(f"- **Description:** {product.description.strip()}\n")
            if product.reference_asset:
                asset_name = Path(product.reference_asset).name if isinstance(product.reference_asset, (str, Path)) else "unknown"
                f.write(f"- **Reference Asset:** `{asset_name}`\n")
            f.write(f"\n")
        
        # Type-specific sections
        if log_type == "asset_generation":
            _write_asset_generation_section(f, generated_assets or [])
        elif log_type == "campaign_generation" and result:
            _write_campaign_generation_section(f, result)
        
        # Footer
        f.write(f"---\n\n")
        f.write(f"*Generated by Creative Automation Pipeline*\n")
    
    log.info("run=%s wrote summary log to %s", run_id, summary_path)
    return summary_path


def _write_asset_generation_section(f, generated_assets: list[str]) -> None:
    """Write the asset generation section to the summary file."""
    f.write(f"## Asset Generation Results\n\n")
    
    if generated_assets:
        f.write(f"**Status:** ✅ Success  \n")
        f.write(f"**Generated Assets:** {len(generated_assets)}\n\n")
        
        f.write(f"### Generated Files\n\n")
        for asset in generated_assets:
            f.write(f"- `{asset}`\n")
        f.write(f"\n")
        
        f.write(f"💡 **Tip:** Copy the generated PNG files to your assets folder to use in future campaign runs.\n\n")
    else:
        f.write(f"**Status:** ℹ️ No assets generated (all products had reference assets)\n\n")


def _write_campaign_generation_section(f, result: dict[str, Any]) -> None:
    """Write the campaign generation section to the summary file."""
    f.write(f"## Campaign Generation Results\n\n")
    
    status = result.get("status", "unknown")
    if status == "complete":
        f.write(f"**Status:** ✅ Complete\n\n")
    else:
        f.write(f"**Status:** ❌ Failed\n")
        if "error" in result:
            f.write(f"**Error:** {result['error']}\n\n")
    
    # Localization info
    localization_info = result.get("localization", {})
    target_language = localization_info.get("target_language")
    
    if target_language:
        f.write(f"### Localization\n\n")
        f.write(f"**Target Language:** {target_language}\n\n")
        
        if localization_info.get("message_translated"):
            f.write(f"**Campaign Message:**\n")
            f.write(f"- Original: _{localization_info.get('original_message', 'N/A')}_\n")
            f.write(f"- Localized: _{localization_info.get('localized_message', 'N/A')}_\n\n")
        
        products_info = localization_info.get("products", {})
        translated_products = [
            slug for slug, info in products_info.items()
            if info.get("translated")
        ]
        
        if translated_products:
            f.write(f"**Translated Product Descriptions:** {len(translated_products)}\n\n")
            for slug in translated_products:
                info = products_info[slug]
                f.write(f"#### {slug}\n")
                f.write(f"- Original: _{info.get('original', 'N/A')}_\n")
                f.write(f"- Localized: _{info.get('localized', 'N/A')}_\n\n")
    else:
        f.write(f"### Localization\n\n")
        f.write(f"ℹ️ No localization required - campaign language matches target region.\n\n")
    
    # Output summary
    outputs = result.get("outputs", {})
    timings = result.get("timings", {})
    
    if outputs:
        f.write(f"### Generated Creatives\n\n")
        
        total_creatives = sum(len(ratios) for ratios in outputs.values())
        f.write(f"**Total Creatives Generated:** {total_creatives}\n\n")
        
        for product_slug, ratios in outputs.items():
            f.write(f"#### {product_slug}\n\n")
            f.write(f"| Aspect Ratio | Generation Time | Dropbox URL |\n")
            f.write(f"|--------------|-----------------|-------------|\n")
            
            for ratio, url in ratios.items():
                timing = timings.get(product_slug, {}).get(ratio, 0)
                f.write(f"| {ratio} | {timing:.1f}s | [View]({url}) |\n")
            
            f.write(f"\n")
    
    # Pipeline log
    pipeline_log = result.get("log", [])
    if pipeline_log:
        f.write(f"### Pipeline Log\n\n")
        f.write(f"```\n")
        for entry in pipeline_log:
            f.write(f"{entry}\n")
        f.write(f"```\n\n")
